name: Build Web

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build System Setup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y squashfs-tools
          sudo npm install -g pnpm

      - name: Build daed-revived-next
        run: |
          git clone https://github.com/daeuniverse/daed-revived-next build --depth=1
          cd build
          commit_id=$(git log --pretty=format:%cd -n 1 --date=short)-$(git log --pretty=format:%h -n 1)
          echo "version=$commit_id" >> "$GITHUB_ENV"
          pnpm install
          STANDALONE=1 pnpm build
          cp -a .next/standalone out
          cp -a .next/static out/.next/
          cp -a public out
          mksquashfs out daed-web-$commit_id.squashfs -comp xz
          tar Jcf daed-web-$commit_id.tar.xz out

      - name: Create release
        uses: ncipollo/release-action@v1.11.1
        with:
          name: daed-web-${{ env.version }}
          allowUpdates: true
          tag: daed-web-${{ env.version }}
          commit: main
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: build/daed-web-${{ env.version }}.*
